name: photo_gallery
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  flutter_staggered_grid_view: ^0.7.0
  flutter_animate: ^4.5.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
